# Generated by Django 3.2.5 on 2021-07-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0336_userstatus_status_emoji"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Normal"),
                    (2, "Resolve Topic Notification"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Normal"),
                    (2, "Resolve Topic Notification"),
                ],
                default=1,
            ),
        ),
    ]
